package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * CartHasItem generated by hbm2java
 */
public class CartHasItem  implements java.io.Serializable {


     private Integer idcartHasItem;
     private Product product;
     private Cart cart;

    public CartHasItem() {
    }

    public CartHasItem(Product product, Cart cart) {
       this.product = product;
       this.cart = cart;
    }
   
    public Integer getIdcartHasItem() {
        return this.idcartHasItem;
    }
    
    public void setIdcartHasItem(Integer idcartHasItem) {
        this.idcartHasItem = idcartHasItem;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }




}


