package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private Set<CartHasItem> cartHasItems = new HashSet<CartHasItem>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Set<CartHasItem> cartHasItems) {
       this.user = user;
       this.cartHasItems = cartHasItems;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<CartHasItem> getCartHasItems() {
        return this.cartHasItems;
    }
    
    public void setCartHasItems(Set<CartHasItem> cartHasItems) {
        this.cartHasItems = cartHasItems;
    }




}


