package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer idcomments;
     private Product product;
     private User user;
     private String comment;
     private Date date;
     private Date time;

    public Comments() {
    }

	
    public Comments(Product product, User user) {
        this.product = product;
        this.user = user;
    }
    public Comments(Product product, User user, String comment, Date date, Date time) {
       this.product = product;
       this.user = user;
       this.comment = comment;
       this.date = date;
       this.time = time;
    }
   
    public Integer getIdcomments() {
        return this.idcomments;
    }
    
    public void setIdcomments(Integer idcomments) {
        this.idcomments = idcomments;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


