package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Disandaddon generated by hbm2java
 */
public class Disandaddon  implements java.io.Serializable {


     private Integer iddisAndAddon;
     private Product product;
     private Date lastUpdateDate;
     private Double discount;
     private Double addon;

    public Disandaddon() {
    }

	
    public Disandaddon(Product product) {
        this.product = product;
    }
    public Disandaddon(Product product, Date lastUpdateDate, Double discount, Double addon) {
       this.product = product;
       this.lastUpdateDate = lastUpdateDate;
       this.discount = discount;
       this.addon = addon;
    }
   
    public Integer getIddisAndAddon() {
        return this.iddisAndAddon;
    }
    
    public void setIddisAndAddon(Integer iddisAndAddon) {
        this.iddisAndAddon = iddisAndAddon;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getAddon() {
        return this.addon;
    }
    
    public void setAddon(Double addon) {
        this.addon = addon;
    }




}


