package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceProduct generated by hbm2java
 */
public class InvoiceProduct  implements java.io.Serializable {


     private Integer idinvoiceProduct;
     private User user;
     private Date date;
     private Date time;
     private Double subTot;
     private Double addonTot;
     private Double disTot;
     private Double total;
     private String status;
     private Set<PurchaseHistory> purchaseHistories = new HashSet<PurchaseHistory>(0);
     private Set<InvoiceProductHasItem> invoiceProductHasItems = new HashSet<InvoiceProductHasItem>(0);

    public InvoiceProduct() {
    }

	
    public InvoiceProduct(User user) {
        this.user = user;
    }
    public InvoiceProduct(User user, Date date, Date time, Double subTot, Double addonTot, Double disTot, Double total, String status, Set<PurchaseHistory> purchaseHistories, Set<InvoiceProductHasItem> invoiceProductHasItems) {
       this.user = user;
       this.date = date;
       this.time = time;
       this.subTot = subTot;
       this.addonTot = addonTot;
       this.disTot = disTot;
       this.total = total;
       this.status = status;
       this.purchaseHistories = purchaseHistories;
       this.invoiceProductHasItems = invoiceProductHasItems;
    }
   
    public Integer getIdinvoiceProduct() {
        return this.idinvoiceProduct;
    }
    
    public void setIdinvoiceProduct(Integer idinvoiceProduct) {
        this.idinvoiceProduct = idinvoiceProduct;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getSubTot() {
        return this.subTot;
    }
    
    public void setSubTot(Double subTot) {
        this.subTot = subTot;
    }
    public Double getAddonTot() {
        return this.addonTot;
    }
    
    public void setAddonTot(Double addonTot) {
        this.addonTot = addonTot;
    }
    public Double getDisTot() {
        return this.disTot;
    }
    
    public void setDisTot(Double disTot) {
        this.disTot = disTot;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<PurchaseHistory> getPurchaseHistories() {
        return this.purchaseHistories;
    }
    
    public void setPurchaseHistories(Set<PurchaseHistory> purchaseHistories) {
        this.purchaseHistories = purchaseHistories;
    }
    public Set<InvoiceProductHasItem> getInvoiceProductHasItems() {
        return this.invoiceProductHasItems;
    }
    
    public void setInvoiceProductHasItems(Set<InvoiceProductHasItem> invoiceProductHasItems) {
        this.invoiceProductHasItems = invoiceProductHasItems;
    }




}


