package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * InvoicePackage generated by hbm2java
 */
public class InvoicePackage  implements java.io.Serializable {


     private Integer idinvoicePackage;
     private SellerHasPackage sellerHasPackage;
     private User user;
     private Date date;
     private String status;

    public InvoicePackage() {
    }

	
    public InvoicePackage(SellerHasPackage sellerHasPackage, User user) {
        this.sellerHasPackage = sellerHasPackage;
        this.user = user;
    }
    public InvoicePackage(SellerHasPackage sellerHasPackage, User user, Date date, String status) {
       this.sellerHasPackage = sellerHasPackage;
       this.user = user;
       this.date = date;
       this.status = status;
    }
   
    public Integer getIdinvoicePackage() {
        return this.idinvoicePackage;
    }
    
    public void setIdinvoicePackage(Integer idinvoicePackage) {
        this.idinvoicePackage = idinvoicePackage;
    }
    public SellerHasPackage getSellerHasPackage() {
        return this.sellerHasPackage;
    }
    
    public void setSellerHasPackage(SellerHasPackage sellerHasPackage) {
        this.sellerHasPackage = sellerHasPackage;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


