package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * InvoiceProductHasItem generated by hbm2java
 */
public class InvoiceProductHasItem  implements java.io.Serializable {


     private Integer idinvoiceProductHasItem;
     private InvoiceProduct invoiceProduct;
     private Product product;

    public InvoiceProductHasItem() {
    }

    public InvoiceProductHasItem(InvoiceProduct invoiceProduct, Product product) {
       this.invoiceProduct = invoiceProduct;
       this.product = product;
    }
   
    public Integer getIdinvoiceProductHasItem() {
        return this.idinvoiceProductHasItem;
    }
    
    public void setIdinvoiceProductHasItem(Integer idinvoiceProductHasItem) {
        this.idinvoiceProductHasItem = idinvoiceProductHasItem;
    }
    public InvoiceProduct getInvoiceProduct() {
        return this.invoiceProduct;
    }
    
    public void setInvoiceProduct(InvoiceProduct invoiceProduct) {
        this.invoiceProduct = invoiceProduct;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


