package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer idmessages;
     private Seller seller;
     private Admin admin;
     private User user;
     private String msgHeading;
     private String msgBody;

    public Messages() {
    }

	
    public Messages(Seller seller, Admin admin, User user) {
        this.seller = seller;
        this.admin = admin;
        this.user = user;
    }
    public Messages(Seller seller, Admin admin, User user, String msgHeading, String msgBody) {
       this.seller = seller;
       this.admin = admin;
       this.user = user;
       this.msgHeading = msgHeading;
       this.msgBody = msgBody;
    }
   
    public Integer getIdmessages() {
        return this.idmessages;
    }
    
    public void setIdmessages(Integer idmessages) {
        this.idmessages = idmessages;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMsgHeading() {
        return this.msgHeading;
    }
    
    public void setMsgHeading(String msgHeading) {
        this.msgHeading = msgHeading;
    }
    public String getMsgBody() {
        return this.msgBody;
    }
    
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }




}


