package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * Notifications generated by hbm2java
 */
public class Notifications  implements java.io.Serializable {


     private Integer idnotifications;
     private User user;
     private String type;
     private String message;
     private String status;

    public Notifications() {
    }

	
    public Notifications(User user) {
        this.user = user;
    }
    public Notifications(User user, String type, String message, String status) {
       this.user = user;
       this.type = type;
       this.message = message;
       this.status = status;
    }
   
    public Integer getIdnotifications() {
        return this.idnotifications;
    }
    
    public void setIdnotifications(Integer idnotifications) {
        this.idnotifications = idnotifications;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


