package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * PRate generated by hbm2java
 */
public class PRate  implements java.io.Serializable {


     private Integer idpRate;
     private Product product;
     private User user;
     private Integer rate;

    public PRate() {
    }

	
    public PRate(Product product, User user) {
        this.product = product;
        this.user = user;
    }
    public PRate(Product product, User user, Integer rate) {
       this.product = product;
       this.user = user;
       this.rate = rate;
    }
   
    public Integer getIdpRate() {
        return this.idpRate;
    }
    
    public void setIdpRate(Integer idpRate) {
        this.idpRate = idpRate;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }




}


