package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * ProductHasSupportOs generated by hbm2java
 */
public class ProductHasSupportOs  implements java.io.Serializable {


     private Integer idproductHasSupportOs;
     private Product product;
     private SupportOs supportOs;

    public ProductHasSupportOs() {
    }

    public ProductHasSupportOs(Product product, SupportOs supportOs) {
       this.product = product;
       this.supportOs = supportOs;
    }
   
    public Integer getIdproductHasSupportOs() {
        return this.idproductHasSupportOs;
    }
    
    public void setIdproductHasSupportOs(Integer idproductHasSupportOs) {
        this.idproductHasSupportOs = idproductHasSupportOs;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public SupportOs getSupportOs() {
        return this.supportOs;
    }
    
    public void setSupportOs(SupportOs supportOs) {
        this.supportOs = supportOs;
    }




}


