package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private Seller seller;
     private Admin admin;
     private SfCategory sfCategory;
     private String sfType;
     private String sfLanguage;
     private String title;
     private String smallDes;
     private String briefDes;
     private String features;
     private String img1;
     private String img2;
     private String img3;
     private String video;
     private String demoZip;
     private String orginalZip;
     private String srs;
     private Boolean returnAccept;
     private Date addDate;
     private Double price;
     private String sellLimit;
     private String status;
     private Set<WishListHasItem> wishListHasItems = new HashSet<WishListHasItem>(0);
     private Set<CartHasItem> cartHasItems = new HashSet<CartHasItem>(0);
     private Set<ProductHasPlatform> productHasPlatforms = new HashSet<ProductHasPlatform>(0);
     private Set<ProductHasSupportOs> productHasSupportOses = new HashSet<ProductHasSupportOs>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<InvoiceProductHasItem> invoiceProductHasItems = new HashSet<InvoiceProductHasItem>(0);
     private Set<PRate> PRates = new HashSet<PRate>(0);
     private Set<Disandaddon> disandaddons = new HashSet<Disandaddon>(0);

    public Product() {
    }

	
    public Product(Seller seller, Admin admin, SfCategory sfCategory) {
        this.seller = seller;
        this.admin = admin;
        this.sfCategory = sfCategory;
    }
    public Product(Seller seller, Admin admin, SfCategory sfCategory, String sfType, String sfLanguage, String title, String smallDes, String briefDes, String features, String img1, String img2, String img3, String video, String demoZip, String orginalZip, String srs, Boolean returnAccept, Date addDate, Double price, String sellLimit, String status, Set<WishListHasItem> wishListHasItems, Set<CartHasItem> cartHasItems, Set<ProductHasPlatform> productHasPlatforms, Set<ProductHasSupportOs> productHasSupportOses, Set<Comments> commentses, Set<InvoiceProductHasItem> invoiceProductHasItems, Set<PRate> PRates, Set<Disandaddon> disandaddons) {
       this.seller = seller;
       this.admin = admin;
       this.sfCategory = sfCategory;
       this.sfType = sfType;
       this.sfLanguage = sfLanguage;
       this.title = title;
       this.smallDes = smallDes;
       this.briefDes = briefDes;
       this.features = features;
       this.img1 = img1;
       this.img2 = img2;
       this.img3 = img3;
       this.video = video;
       this.demoZip = demoZip;
       this.orginalZip = orginalZip;
       this.srs = srs;
       this.returnAccept = returnAccept;
       this.addDate = addDate;
       this.price = price;
       this.sellLimit = sellLimit;
       this.status = status;
       this.wishListHasItems = wishListHasItems;
       this.cartHasItems = cartHasItems;
       this.productHasPlatforms = productHasPlatforms;
       this.productHasSupportOses = productHasSupportOses;
       this.commentses = commentses;
       this.invoiceProductHasItems = invoiceProductHasItems;
       this.PRates = PRates;
       this.disandaddons = disandaddons;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public SfCategory getSfCategory() {
        return this.sfCategory;
    }
    
    public void setSfCategory(SfCategory sfCategory) {
        this.sfCategory = sfCategory;
    }
    public String getSfType() {
        return this.sfType;
    }
    
    public void setSfType(String sfType) {
        this.sfType = sfType;
    }
    public String getSfLanguage() {
        return this.sfLanguage;
    }
    
    public void setSfLanguage(String sfLanguage) {
        this.sfLanguage = sfLanguage;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSmallDes() {
        return this.smallDes;
    }
    
    public void setSmallDes(String smallDes) {
        this.smallDes = smallDes;
    }
    public String getBriefDes() {
        return this.briefDes;
    }
    
    public void setBriefDes(String briefDes) {
        this.briefDes = briefDes;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }
    public String getImg1() {
        return this.img1;
    }
    
    public void setImg1(String img1) {
        this.img1 = img1;
    }
    public String getImg2() {
        return this.img2;
    }
    
    public void setImg2(String img2) {
        this.img2 = img2;
    }
    public String getImg3() {
        return this.img3;
    }
    
    public void setImg3(String img3) {
        this.img3 = img3;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public String getDemoZip() {
        return this.demoZip;
    }
    
    public void setDemoZip(String demoZip) {
        this.demoZip = demoZip;
    }
    public String getOrginalZip() {
        return this.orginalZip;
    }
    
    public void setOrginalZip(String orginalZip) {
        this.orginalZip = orginalZip;
    }
    public String getSrs() {
        return this.srs;
    }
    
    public void setSrs(String srs) {
        this.srs = srs;
    }
    public Boolean getReturnAccept() {
        return this.returnAccept;
    }
    
    public void setReturnAccept(Boolean returnAccept) {
        this.returnAccept = returnAccept;
    }
    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getSellLimit() {
        return this.sellLimit;
    }
    
    public void setSellLimit(String sellLimit) {
        this.sellLimit = sellLimit;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<WishListHasItem> getWishListHasItems() {
        return this.wishListHasItems;
    }
    
    public void setWishListHasItems(Set<WishListHasItem> wishListHasItems) {
        this.wishListHasItems = wishListHasItems;
    }
    public Set<CartHasItem> getCartHasItems() {
        return this.cartHasItems;
    }
    
    public void setCartHasItems(Set<CartHasItem> cartHasItems) {
        this.cartHasItems = cartHasItems;
    }
    public Set<ProductHasPlatform> getProductHasPlatforms() {
        return this.productHasPlatforms;
    }
    
    public void setProductHasPlatforms(Set<ProductHasPlatform> productHasPlatforms) {
        this.productHasPlatforms = productHasPlatforms;
    }
    public Set<ProductHasSupportOs> getProductHasSupportOses() {
        return this.productHasSupportOses;
    }
    
    public void setProductHasSupportOses(Set<ProductHasSupportOs> productHasSupportOses) {
        this.productHasSupportOses = productHasSupportOses;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<InvoiceProductHasItem> getInvoiceProductHasItems() {
        return this.invoiceProductHasItems;
    }
    
    public void setInvoiceProductHasItems(Set<InvoiceProductHasItem> invoiceProductHasItems) {
        this.invoiceProductHasItems = invoiceProductHasItems;
    }
    public Set<PRate> getPRates() {
        return this.PRates;
    }
    
    public void setPRates(Set<PRate> PRates) {
        this.PRates = PRates;
    }
    public Set<Disandaddon> getDisandaddons() {
        return this.disandaddons;
    }
    
    public void setDisandaddons(Set<Disandaddon> disandaddons) {
        this.disandaddons = disandaddons;
    }
    public void getBriefDes(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


