package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * PurchaseHistory generated by hbm2java
 */
public class PurchaseHistory  implements java.io.Serializable {


     private Integer idpurchaseHistory;
     private InvoiceProduct invoiceProduct;

    public PurchaseHistory() {
    }

    public PurchaseHistory(InvoiceProduct invoiceProduct) {
       this.invoiceProduct = invoiceProduct;
    }
   
    public Integer getIdpurchaseHistory() {
        return this.idpurchaseHistory;
    }
    
    public void setIdpurchaseHistory(Integer idpurchaseHistory) {
        this.idpurchaseHistory = idpurchaseHistory;
    }
    public InvoiceProduct getInvoiceProduct() {
        return this.invoiceProduct;
    }
    
    public void setInvoiceProduct(InvoiceProduct invoiceProduct) {
        this.invoiceProduct = invoiceProduct;
    }




}


