package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ReqProject generated by hbm2java
 */
public class ReqProject  implements java.io.Serializable {


     private Integer idreqProject;
     private SfCategory sfCategory;
     private User user;
     private Date date;
     private String title;
     private String sfPlatform;
     private String des;
     private Double wishPrice;

    public ReqProject() {
    }

	
    public ReqProject(SfCategory sfCategory, User user) {
        this.sfCategory = sfCategory;
        this.user = user;
    }
    public ReqProject(SfCategory sfCategory, User user, Date date, String title, String sfPlatform, String des, Double wishPrice) {
       this.sfCategory = sfCategory;
       this.user = user;
       this.date = date;
       this.title = title;
       this.sfPlatform = sfPlatform;
       this.des = des;
       this.wishPrice = wishPrice;
    }
   
    public Integer getIdreqProject() {
        return this.idreqProject;
    }
    
    public void setIdreqProject(Integer idreqProject) {
        this.idreqProject = idreqProject;
    }
    public SfCategory getSfCategory() {
        return this.sfCategory;
    }
    
    public void setSfCategory(SfCategory sfCategory) {
        this.sfCategory = sfCategory;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSfPlatform() {
        return this.sfPlatform;
    }
    
    public void setSfPlatform(String sfPlatform) {
        this.sfPlatform = sfPlatform;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Double getWishPrice() {
        return this.wishPrice;
    }
    
    public void setWishPrice(Double wishPrice) {
        this.wishPrice = wishPrice;
    }




}


