package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * SavedSeller generated by hbm2java
 */
public class SavedSeller  implements java.io.Serializable {


     private Integer idsavedSeller;
     private Seller seller;
     private User user;

    public SavedSeller() {
    }

    public SavedSeller(Seller seller, User user) {
       this.seller = seller;
       this.user = user;
    }
   
    public Integer getIdsavedSeller() {
        return this.idsavedSeller;
    }
    
    public void setIdsavedSeller(Integer idsavedSeller) {
        this.idsavedSeller = idsavedSeller;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


