package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SellerPackage generated by hbm2java
 */
public class SellerPackage  implements java.io.Serializable {


     private Integer idpackage;
     private String name;
     private Integer maxAddTime;
     private Integer validMonths;
     private Integer profitPercentage;
     private Double price;
     private Set<SellerHasPackage> sellerHasPackages = new HashSet<SellerHasPackage>(0);

    public SellerPackage() {
    }

    public SellerPackage(String name, Integer maxAddTime, Integer validMonths, Integer profitPercentage, Double price, Set<SellerHasPackage> sellerHasPackages) {
       this.name = name;
       this.maxAddTime = maxAddTime;
       this.validMonths = validMonths;
       this.profitPercentage = profitPercentage;
       this.price = price;
       this.sellerHasPackages = sellerHasPackages;
    }
   
    public Integer getIdpackage() {
        return this.idpackage;
    }
    
    public void setIdpackage(Integer idpackage) {
        this.idpackage = idpackage;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getMaxAddTime() {
        return this.maxAddTime;
    }
    
    public void setMaxAddTime(Integer maxAddTime) {
        this.maxAddTime = maxAddTime;
    }
    public Integer getValidMonths() {
        return this.validMonths;
    }
    
    public void setValidMonths(Integer validMonths) {
        this.validMonths = validMonths;
    }
    public Integer getProfitPercentage() {
        return this.profitPercentage;
    }
    
    public void setProfitPercentage(Integer profitPercentage) {
        this.profitPercentage = profitPercentage;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Set<SellerHasPackage> getSellerHasPackages() {
        return this.sellerHasPackages;
    }
    
    public void setSellerHasPackages(Set<SellerHasPackage> sellerHasPackages) {
        this.sellerHasPackages = sellerHasPackages;
    }




}


