package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Seller generated by hbm2java
 */
public class Seller  implements java.io.Serializable {


     private Integer idseller;
     private User user;
     private String status;
     private Set<SRate> SRates = new HashSet<SRate>(0);
     private Set<SavedSeller> savedSellers = new HashSet<SavedSeller>(0);
     private Set<SellerHasPackage> sellerHasPackages = new HashSet<SellerHasPackage>(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set<Messages> messageses = new HashSet<Messages>(0);

    public Seller() {
    }

	
    public Seller(User user) {
        this.user = user;
    }
    public Seller(User user, String status, Set<SRate> SRates, Set<SavedSeller> savedSellers, Set<SellerHasPackage> sellerHasPackages, Set<Product> products, Set<Messages> messageses) {
       this.user = user;
       this.status = status;
       this.SRates = SRates;
       this.savedSellers = savedSellers;
       this.sellerHasPackages = sellerHasPackages;
       this.products = products;
       this.messageses = messageses;
    }
   
    public Integer getIdseller() {
        return this.idseller;
    }
    
    public void setIdseller(Integer idseller) {
        this.idseller = idseller;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<SRate> getSRates() {
        return this.SRates;
    }
    
    public void setSRates(Set<SRate> SRates) {
        this.SRates = SRates;
    }
    public Set<SavedSeller> getSavedSellers() {
        return this.savedSellers;
    }
    
    public void setSavedSellers(Set<SavedSeller> savedSellers) {
        this.savedSellers = savedSellers;
    }
    public Set<SellerHasPackage> getSellerHasPackages() {
        return this.sellerHasPackages;
    }
    
    public void setSellerHasPackages(Set<SellerHasPackage> sellerHasPackages) {
        this.sellerHasPackages = sellerHasPackages;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }




}


