package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SfCategory generated by hbm2java
 */
public class SfCategory  implements java.io.Serializable {


     private Integer idsfCategory;
     private String categoryName;
     private Set<ReqProject> reqProjects = new HashSet<ReqProject>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public SfCategory() {
    }

    public SfCategory(String categoryName, Set<ReqProject> reqProjects, Set<Product> products) {
       this.categoryName = categoryName;
       this.reqProjects = reqProjects;
       this.products = products;
    }
   
    public Integer getIdsfCategory() {
        return this.idsfCategory;
    }
    
    public void setIdsfCategory(Integer idsfCategory) {
        this.idsfCategory = idsfCategory;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set<ReqProject> getReqProjects() {
        return this.reqProjects;
    }
    
    public void setReqProjects(Set<ReqProject> reqProjects) {
        this.reqProjects = reqProjects;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


