package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SfPlatform generated by hbm2java
 */
public class SfPlatform  implements java.io.Serializable {


     private Integer idsfPlatform;
     private String name;
     private Set<ProductHasPlatform> productHasPlatforms = new HashSet<ProductHasPlatform>(0);

    public SfPlatform() {
    }

    public SfPlatform(String name, Set<ProductHasPlatform> productHasPlatforms) {
       this.name = name;
       this.productHasPlatforms = productHasPlatforms;
    }
   
    public Integer getIdsfPlatform() {
        return this.idsfPlatform;
    }
    
    public void setIdsfPlatform(Integer idsfPlatform) {
        this.idsfPlatform = idsfPlatform;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ProductHasPlatform> getProductHasPlatforms() {
        return this.productHasPlatforms;
    }
    
    public void setProductHasPlatforms(Set<ProductHasPlatform> productHasPlatforms) {
        this.productHasPlatforms = productHasPlatforms;
    }




}


