package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * SRate generated by hbm2java
 */
public class SRate  implements java.io.Serializable {


     private Integer idsRate;
     private Seller seller;
     private User user;
     private Integer rate;

    public SRate() {
    }

	
    public SRate(Seller seller, User user) {
        this.seller = seller;
        this.user = user;
    }
    public SRate(Seller seller, User user, Integer rate) {
       this.seller = seller;
       this.user = user;
       this.rate = rate;
    }
   
    public Integer getIdsRate() {
        return this.idsRate;
    }
    
    public void setIdsRate(Integer idsRate) {
        this.idsRate = idsRate;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }




}


