package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SupportOs generated by hbm2java
 */
public class SupportOs  implements java.io.Serializable {


     private Integer idsupportOs;
     private String name;
     private Set<ProductHasSupportOs> productHasSupportOses = new HashSet<ProductHasSupportOs>(0);

    public SupportOs() {
    }

    public SupportOs(String name, Set<ProductHasSupportOs> productHasSupportOses) {
       this.name = name;
       this.productHasSupportOses = productHasSupportOses;
    }
   
    public Integer getIdsupportOs() {
        return this.idsupportOs;
    }
    
    public void setIdsupportOs(Integer idsupportOs) {
        this.idsupportOs = idsupportOs;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ProductHasSupportOs> getProductHasSupportOses() {
        return this.productHasSupportOses;
    }
    
    public void setProductHasSupportOses(Set<ProductHasSupportOs> productHasSupportOses) {
        this.productHasSupportOses = productHasSupportOses;
    }




}


