package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String type;
     private String firstName;
     private String lastName;
     private String street;
     private String zip;
     private String city;
     private String country;
     private String mobile;
     private String imgUrl;
     private String email;
     private String password;
     private String emailVerifyCode;
     private String status;
     private Set<Notifications> notificationses = new HashSet<Notifications>(0);
     private Set<SRate> SRates = new HashSet<SRate>(0);
     private Set<SavedSeller> savedSellers = new HashSet<SavedSeller>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Seller> sellers = new HashSet<Seller>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Messages> messageses = new HashSet<Messages>(0);
     private Set<InvoicePackage> invoicePackages = new HashSet<InvoicePackage>(0);
     private Set<WishList> wishLists = new HashSet<WishList>(0);
     private Set<PRate> PRates = new HashSet<PRate>(0);
     private Set<ReqProject> reqProjects = new HashSet<ReqProject>(0);
     private Set<InvoiceProduct> invoiceProducts = new HashSet<InvoiceProduct>(0);

    public User() {
    }

    public User(String type, String firstName, String lastName, String street, String zip, String city, String country, String mobile, String imgUrl, String email, String password, String emailVerifyCode, String status, Set<Notifications> notificationses, Set<SRate> SRates, Set<SavedSeller> savedSellers, Set<Comments> commentses, Set<Seller> sellers, Set<Cart> carts, Set<Messages> messageses, Set<InvoicePackage> invoicePackages, Set<WishList> wishLists, Set<PRate> PRates, Set<ReqProject> reqProjects, Set<InvoiceProduct> invoiceProducts) {
       this.type = type;
       this.firstName = firstName;
       this.lastName = lastName;
       this.street = street;
       this.zip = zip;
       this.city = city;
       this.country = country;
       this.mobile = mobile;
       this.imgUrl = imgUrl;
       this.email = email;
       this.password = password;
       this.emailVerifyCode = emailVerifyCode;
       this.status = status;
       this.notificationses = notificationses;
       this.SRates = SRates;
       this.savedSellers = savedSellers;
       this.commentses = commentses;
       this.sellers = sellers;
       this.carts = carts;
       this.messageses = messageses;
       this.invoicePackages = invoicePackages;
       this.wishLists = wishLists;
       this.PRates = PRates;
       this.reqProjects = reqProjects;
       this.invoiceProducts = invoiceProducts;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailVerifyCode() {
        return this.emailVerifyCode;
    }
    
    public void setEmailVerifyCode(String emailVerifyCode) {
        this.emailVerifyCode = emailVerifyCode;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Notifications> getNotificationses() {
        return this.notificationses;
    }
    
    public void setNotificationses(Set<Notifications> notificationses) {
        this.notificationses = notificationses;
    }
    public Set<SRate> getSRates() {
        return this.SRates;
    }
    
    public void setSRates(Set<SRate> SRates) {
        this.SRates = SRates;
    }
    public Set<SavedSeller> getSavedSellers() {
        return this.savedSellers;
    }
    
    public void setSavedSellers(Set<SavedSeller> savedSellers) {
        this.savedSellers = savedSellers;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<Seller> getSellers() {
        return this.sellers;
    }
    
    public void setSellers(Set<Seller> sellers) {
        this.sellers = sellers;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }
    public Set<InvoicePackage> getInvoicePackages() {
        return this.invoicePackages;
    }
    
    public void setInvoicePackages(Set<InvoicePackage> invoicePackages) {
        this.invoicePackages = invoicePackages;
    }
    public Set<WishList> getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set<WishList> wishLists) {
        this.wishLists = wishLists;
    }
    public Set<PRate> getPRates() {
        return this.PRates;
    }
    
    public void setPRates(Set<PRate> PRates) {
        this.PRates = PRates;
    }
    public Set<ReqProject> getReqProjects() {
        return this.reqProjects;
    }
    
    public void setReqProjects(Set<ReqProject> reqProjects) {
        this.reqProjects = reqProjects;
    }
    public Set<InvoiceProduct> getInvoiceProducts() {
        return this.invoiceProducts;
    }
    
    public void setInvoiceProducts(Set<InvoiceProduct> invoiceProducts) {
        this.invoiceProducts = invoiceProducts;
    }




}


