package pojos;
// Generated Jun 4, 2018 3:43:42 PM by Hibernate Tools 3.6.0



/**
 * WishListHasItem generated by hbm2java
 */
public class WishListHasItem  implements java.io.Serializable {


     private Integer idwishListHasItem;
     private WishList wishList;
     private Product product;

    public WishListHasItem() {
    }

    public WishListHasItem(WishList wishList, Product product) {
       this.wishList = wishList;
       this.product = product;
    }
   
    public Integer getIdwishListHasItem() {
        return this.idwishListHasItem;
    }
    
    public void setIdwishListHasItem(Integer idwishListHasItem) {
        this.idwishListHasItem = idwishListHasItem;
    }
    public WishList getWishList() {
        return this.wishList;
    }
    
    public void setWishList(WishList wishList) {
        this.wishList = wishList;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


